#pragma once

enum ata_fw_error
{
	ATA_FW_ERR_UNINITIALIZED = -1,
	ATA_FW_ERR_SUCCESS = 0,
	ATA_FW_ERR_NULL_PARAMETER,
	ATA_FW_ERR_INVALID_PARAMETER,
	ATA_FW_ERR_EXTERNAL_FUNCTION_FAILED,
	ATA_FW_ERR_RESPONSE_ERROR,
	ATA_FW_ERR_NO_SPACE,
};
